version: '2'
services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-medt-api

  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-medt-backend

  cronjob:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-cronjob
    links:
      - backend
    depends_on:
      - backend

  nginx-server:
    restart: always
    image: nginx:1.11.9
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./config/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - api
      - backend
    depends_on:
      - api
      - backend
