version: '2'
services:
  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
  redis:
    image: redis:3.0-alpine
  nginx-server:
    restart: always
    image: nginx:1.11.9
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./config/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - backend
      - redis
    depends_on:
      - backend